# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-13 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5')),
                ('descp', models.CharField(max_length=500, verbose_name='\u6587\u7ae0\u63cf\u8ff0')),
                ('view_nums', models.IntegerField(default=0, verbose_name='\u67e5\u770b\u6570')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Type', verbose_name='\u7c7b\u578b')),
            ],
        ),
    ]
