# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170513_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumresource',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], default='published', max_length=15),
        ),
    ]
