# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
