# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_forum_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Forum')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u4efb\u52a1',
                'verbose_name_plural': '\u8bfe\u7a0b\u4efb\u52a1',
            },
        ),
    ]
