# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 19:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
