# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 20:34
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_task_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_time', models.DateField(auto_now_add=True, db_index=True)),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u56de\u7b54\u8005')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Task', verbose_name='\u6240\u5c5e\u4efb\u52a1')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u56de\u7b54',
                'verbose_name_plural': '\u4efb\u52a1\u56de\u7b54',
            },
        ),
    ]
