# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-20 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_taskresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
    ]
